spring:
  batch:
    job:
      names: {job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/searchstudy?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 1234